-- PharmFlow single-pharmacy schema. Run once in Supabase SQL Editor.

create table if not exists public.app_settings (
  id integer primary key default 1 check (id = 1),
  greeting text not null default '안녕하세요.',
  ending text not null default '확인 부탁드립니다.',
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.vendor_contacts (
  vendor text primary key,
  contact_name text not null default '',
  phone text not null default '',
  office_phone text not null default '',
  website text not null default '',
  order_method text not null default '카카오톡',
  order_deadline text not null default '',
  note text not null default '',
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.shortage_items (
  id bigint generated by default as identity primary key,
  item_name text not null,
  status text not null default '품절',
  vendors_checked text not null default '',
  expected_date date,
  note text not null default '',
  active boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.order_batches (
  id bigint generated by default as identity primary key,
  order_date date not null default current_date,
  file_name text not null default '',
  total_items integer not null default 0,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.order_batches(id) on delete cascade,
  vendor text not null,
  item_name text not null,
  quantity text not null,
  category text not null default '',
  source_sheet text not null default '',
  source_row integer,
  created_at timestamptz not null default now()
);

insert into public.app_settings (id) values (1) on conflict (id) do nothing;

alter table public.app_settings enable row level security;
alter table public.vendor_contacts enable row level security;
alter table public.shortage_items enable row level security;
alter table public.order_batches enable row level security;
alter table public.order_items enable row level security;

-- Single-pharmacy operation: every authenticated staff account shares the same data.
drop policy if exists "authenticated full access app_settings" on public.app_settings;
create policy "authenticated full access app_settings" on public.app_settings for all to authenticated using (true) with check (true);

drop policy if exists "authenticated full access vendor_contacts" on public.vendor_contacts;
create policy "authenticated full access vendor_contacts" on public.vendor_contacts for all to authenticated using (true) with check (true);

drop policy if exists "authenticated full access shortage_items" on public.shortage_items;
create policy "authenticated full access shortage_items" on public.shortage_items for all to authenticated using (true) with check (true);

drop policy if exists "authenticated full access order_batches" on public.order_batches;
create policy "authenticated full access order_batches" on public.order_batches for all to authenticated using (true) with check (true);

drop policy if exists "authenticated full access order_items" on public.order_items;
create policy "authenticated full access order_items" on public.order_items for all to authenticated using (true) with check (true);

create index if not exists order_batches_order_date_idx on public.order_batches(order_date);
create index if not exists order_items_batch_id_idx on public.order_items(batch_id);
create index if not exists order_items_vendor_idx on public.order_items(vendor);
create index if not exists order_items_item_name_idx on public.order_items(item_name);
create index if not exists shortage_items_active_idx on public.shortage_items(active);
