-- PharmFlow v1.3: 관리자/직원 권한, 가입 승인, 감사 로그
-- 기존 데이터는 유지됩니다. Supabase SQL Editor에서 한 번 실행하세요.

create table if not exists public.staff_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  display_name text not null default '',
  role text not null default 'employee' check (role in ('admin','employee')),
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text not null default '',
  action text not null,
  target_type text not null default '',
  target_name text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- 신규 가입자는 직원/승인대기 상태로 프로필 자동 생성
create or replace function public.handle_new_staff_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.staff_profiles (id, email, display_name, role, is_active)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'display_name', ''),
    'employee',
    false
  )
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_staff_profile on auth.users;
create trigger on_auth_user_created_staff_profile
after insert or update of email on auth.users
for each row execute procedure public.handle_new_staff_user();

-- 기존 가입자 프로필 생성
insert into public.staff_profiles (id, email, display_name, role, is_active)
select id, coalesce(email,''), '', 'employee', false
from auth.users
on conflict (id) do update set email = excluded.email;

-- 가장 먼저 가입한 계정을 최초 관리자로 지정
with first_user as (
  select id from auth.users order by created_at asc limit 1
)
update public.staff_profiles
set role = 'admin', is_active = true, updated_at = now()
where id in (select id from first_user);

-- 권한 판정 함수
create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.staff_profiles
    where id = uid and role = 'admin' and is_active = true
  );
$$;

create or replace function public.is_active_staff(uid uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.staff_profiles
    where id = uid and is_active = true
  );
$$;

grant execute on function public.is_admin(uuid) to authenticated;
grant execute on function public.is_active_staff(uuid) to authenticated;

alter table public.staff_profiles enable row level security;
alter table public.audit_logs enable row level security;

-- 프로필: 본인은 자신의 상태를 볼 수 있고, 관리자는 전체 조회/수정
DROP POLICY IF EXISTS "staff profiles select" ON public.staff_profiles;
CREATE POLICY "staff profiles select" ON public.staff_profiles
FOR SELECT TO authenticated
USING (id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS "staff profiles admin update" ON public.staff_profiles;
CREATE POLICY "staff profiles admin update" ON public.staff_profiles
FOR UPDATE TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

-- 감사 로그: 활성 직원은 기록, 관리자만 조회
DROP POLICY IF EXISTS "audit active insert" ON public.audit_logs;
CREATE POLICY "audit active insert" ON public.audit_logs
FOR INSERT TO authenticated
WITH CHECK (public.is_active_staff() AND actor_id = auth.uid());

DROP POLICY IF EXISTS "audit admin select" ON public.audit_logs;
CREATE POLICY "audit admin select" ON public.audit_logs
FOR SELECT TO authenticated
USING (public.is_admin());

-- 기존의 지나치게 넓은 정책 제거
DROP POLICY IF EXISTS "authenticated full access app_settings" ON public.app_settings;
DROP POLICY IF EXISTS "authenticated full access vendor_contacts" ON public.vendor_contacts;
DROP POLICY IF EXISTS "authenticated full access shortage_items" ON public.shortage_items;
DROP POLICY IF EXISTS "authenticated full access order_batches" ON public.order_batches;
DROP POLICY IF EXISTS "authenticated full access order_items" ON public.order_items;

-- 설정: 활성 직원 조회, 관리자만 수정
DROP POLICY IF EXISTS "settings active read" ON public.app_settings;
CREATE POLICY "settings active read" ON public.app_settings
FOR SELECT TO authenticated USING (public.is_active_staff());
DROP POLICY IF EXISTS "settings admin insert" ON public.app_settings;
CREATE POLICY "settings admin insert" ON public.app_settings
FOR INSERT TO authenticated WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "settings admin update" ON public.app_settings;
CREATE POLICY "settings admin update" ON public.app_settings
FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 거래처: 활성 직원 조회, 관리자만 수정
DROP POLICY IF EXISTS "contacts active read" ON public.vendor_contacts;
CREATE POLICY "contacts active read" ON public.vendor_contacts
FOR SELECT TO authenticated USING (public.is_active_staff());
DROP POLICY IF EXISTS "contacts admin insert" ON public.vendor_contacts;
CREATE POLICY "contacts admin insert" ON public.vendor_contacts
FOR INSERT TO authenticated WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "contacts admin update" ON public.vendor_contacts;
CREATE POLICY "contacts admin update" ON public.vendor_contacts
FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "contacts admin delete" ON public.vendor_contacts;
CREATE POLICY "contacts admin delete" ON public.vendor_contacts
FOR DELETE TO authenticated USING (public.is_admin());

-- 품절: 활성 직원 모두 조회/등록/수정, 삭제는 관리자
DROP POLICY IF EXISTS "shortage active read" ON public.shortage_items;
CREATE POLICY "shortage active read" ON public.shortage_items
FOR SELECT TO authenticated USING (public.is_active_staff());
DROP POLICY IF EXISTS "shortage active insert" ON public.shortage_items;
CREATE POLICY "shortage active insert" ON public.shortage_items
FOR INSERT TO authenticated WITH CHECK (public.is_active_staff() AND created_by = auth.uid());
DROP POLICY IF EXISTS "shortage active update" ON public.shortage_items;
CREATE POLICY "shortage active update" ON public.shortage_items
FOR UPDATE TO authenticated USING (public.is_active_staff()) WITH CHECK (public.is_active_staff());
DROP POLICY IF EXISTS "shortage admin delete" ON public.shortage_items;
CREATE POLICY "shortage admin delete" ON public.shortage_items
FOR DELETE TO authenticated USING (public.is_admin());

-- 주문이력: 활성 직원 조회/등록, 삭제는 관리자
DROP POLICY IF EXISTS "batches active read" ON public.order_batches;
CREATE POLICY "batches active read" ON public.order_batches
FOR SELECT TO authenticated USING (public.is_active_staff());
DROP POLICY IF EXISTS "batches active insert" ON public.order_batches;
CREATE POLICY "batches active insert" ON public.order_batches
FOR INSERT TO authenticated WITH CHECK (public.is_active_staff() AND created_by = auth.uid());
DROP POLICY IF EXISTS "batches admin delete" ON public.order_batches;
CREATE POLICY "batches admin delete" ON public.order_batches
FOR DELETE TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS "items active read" ON public.order_items;
CREATE POLICY "items active read" ON public.order_items
FOR SELECT TO authenticated USING (public.is_active_staff());
DROP POLICY IF EXISTS "items active insert" ON public.order_items;
CREATE POLICY "items active insert" ON public.order_items
FOR INSERT TO authenticated WITH CHECK (
  public.is_active_staff()
  AND exists (
    select 1 from public.order_batches b
    where b.id = batch_id and b.created_by = auth.uid()
  )
);
DROP POLICY IF EXISTS "items admin delete" ON public.order_items;
CREATE POLICY "items admin delete" ON public.order_items
FOR DELETE TO authenticated USING (public.is_admin());

create index if not exists staff_profiles_role_idx on public.staff_profiles(role, is_active);
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
